In [1]:
import pandas as pd
import numpy as np

In [7]:
np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples -  n_class_0

In [8]:
n_class_0,n_class_1

(900, 100)

In [10]:
#CREATING A DATAFRAM WITH IMBALANCE DATASET

class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size = n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size = n_class_0),
    'target': [0] * n_class_0})


class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size = n_class_1),
    'feature_2': np.random.normal(loc=0, scale=1, size = n_class_1),
    'target': [1] * n_class_1
})

In [12]:
df = pd.concat([class_0, class_1]).reset_index(drop=True)

In [13]:
df.head()

   feature_1  feature_2  target
0  -1.774224   0.285744       0
1  -1.201377   0.333279       0
2   1.096257   0.531807       0
3   0.861037  -0.354766       0
4  -1.520367  -1.120815       0

In [14]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [16]:
#Upsampling


df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [17]:
from sklearn.utils import resample
resample(df_minority, replace = True,
         n_samples = len(df_majority),
        random_state = 42
        )

     feature_1  feature_2  target
951   0.905343  -0.504849       1
992   0.000977  -0.185167       1
914  -0.072043   0.280911       1
971   0.819483   0.964646       1
960   0.456515  -0.166472       1
..         ...        ...     ...
952  -0.233356  -0.467775       1
965  -0.472670   0.182477       1
976   0.463277  -1.204384       1
942   0.930412  -0.932647       1
974  -0.133168   0.723282       1

[900 rows x 3 columns]